---
# tasks file for setup_ipv6_linux
- name: Enable IPv6
  sysctl:
    name: "{{ item }}"
    value: 0
    state: present
    reload: true
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
